### PR TITLE
Replaced ttp:frameRateMultipler with ttp:frameRateMultiplier

### LINKED ISSUE #236: ttp:frameRateMultiplier typo
At multiple locations within the document, the attribute `ttp:frameRateMultiplier` is misspelled as `ttp:frameRateMultipler`.

I opened a similar issue for TTML2: w3c/ttml2#287.

### PR DESCRIPTION
**Pull request by palemieux**
Close #236

### CODE REVIEW

**Review by skynavga — COMMENTED** [review]
Why so many unrelated changes in ttml1.html?

**Comment by palemieux** [comment]
> Why so many unrelated changes in ttml1.html?

The build does not work on one of my system apparently. This will be moot once Travis generates the artifacts per https://github.com/w3c/ttml1/pull/262 .

**Review by nigelmegitt — APPROVED** [review]
Editorial. Looks good to me (the XML fix, not the build artefacts).

**Review by skynavga — APPROVED** [review]

**Comment by nigelmegitt** [comment]
Built version of this PR is visible at https://rawgit.com/w3c/ttml1/issue-236-frameRateMultiplier-mispelled-build/index.html

**Pull request merged**
