### PR TITLE
Update stylesheet to match TTML2

### LINKED ISSUE #265: Update stylesheet
The stylesheet etc needs to be updated to match the current W3C publishing rules. This has been done for TTML2 so there's an example there for how to do it.

### PR DESCRIPTION
**Pull request by palemieux**
Closes #265

### CODE REVIEW

**Comment by nigelmegitt** [comment]
This didn't build because travisCI became deactivated on this repo. Need to fiddle with it a bit to encourage the build...

**Comment by nigelmegitt** [comment]
Built version at https://rawgit.com/w3c/ttml1/issue-265-update-stylesheet-build/index.html

**Review by nigelmegitt — COMMENTED** [review]
Looking good generally - I see that the example in tts:overflow, ironically, overflows quite a bit - is there something we need to do to make it scrollable or edit the example XML so the lines are shorter?

**Comment by palemieux** [comment]
@nigelmegitt Added https://github.com/w3c/ttml1/pull/338#pullrequestreview-94320353 at https://github.com/w3c/ttml1/issues/341

**Review by nigelmegitt — APPROVED** [review]

**Pull request merged**
