### PR TITLE
Add travis build status icon

### PR DESCRIPTION
**Pull request by nigelmegitt**
Adds the travis build status icon to the readme.

### CODE REVIEW

**Comment by skynavga** [comment]
What is meaning of [NO TICKET] in title of this PR?

**Comment by nigelmegitt** [comment]
It just means it's a pull request with no issue attached. Just as a hint.

**Comment by skynavga** [comment]
In that case, I would prefer a label be used, such as "no issue". I'd like
to avoid using [] parentheticals as a cheap form of a label. Also, the word
"ticket" has no meaning in this context.

**Comment by nigelmegitt** [comment]
Changed the issue title and added a label as requested.

**Review by skynavga — APPROVED** [review]
Thanks.

**Pull request merged**
