### PR TITLE
Issue 0237 css2 reference

### PR DESCRIPTION
**Pull request by skynavga**
Downgrade CSS2 reference to informative since there was effectively no normative use. This also removes a potential reading ambiguity regarding which version of CSS is referenced, i.e., XSL-FO 1.1 references the original CSS2, while the [CSS2] reference in TTML refers to the newer CSS2.1.

### CODE REVIEW

**Comment by palemieux** [comment]
I am not sure why CSS2.1 needs to be referenced, but perhaps it is already too late since Second Edition was published with that reference.

LGTM anyhow.

**Review by nigelmegitt — APPROVED** [review]
Looks good to me.

**Review by palemieux — APPROVED** [review]

**Comment by skynavga** [comment]
Approved for merge in WG.

**Comment by skynavga** [comment]
See #237.

**Pull request merged**
