### PR TITLE
Add Media timing section

### LINKED ISSUE #300: Clarify timing concepts in relation to SMIL
See w3c/ttml2#135 and pull request https://github.com/w3c/ttml2/pull/143 that led to [TTML2 §12.4.1 Media Timing](https://w3c.github.io/ttml2/spec/ttml2.html#semantics-media-timing) 

Should we also apply the same edits to TTML1 Third Edition? 

I see no reason why not. The SMIL reference would need to be made consistent with the TTML1 SMIL 2.1 reference, unless we also make TTML1 Third Edition reference SMIL 3. The rest of the section is equally true and useful for TTML1 as for TTML2.

### PR DESCRIPTION
**Pull request by nigelmegitt**
Closes #300 by applying the same changes as in w3c/ttml2#143 with the exception that terminology references are in `<emph>` elements rather than navigable `<loc>` elements.

### CODE REVIEW

**Comment by nigelmegitt** [comment]
Build available at https://rawgit.com/w3c/ttml1/issue-0300-media-timing-semantics-build/index.html

Diff at https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fttml1%2Findex.html&doc2=https%3A%2F%2Frawgit.com%2Fw3c%2Fttml1%2Fissue-0300-media-timing-semantics-build%2Findex.html

**Review by skynavga — CHANGES_REQUESTED** [review]
To be consistent with plans for this material in TTML2, this material needs to be re-packaged as a non-normative sub-section of Appendix N.2. See https://github.com/w3c/ttml2/issues/378.

**Comment by nigelmegitt** [comment]
@skynavga I disagree - rather the appendix should be moved in TTML2, as per my https://github.com/w3c/ttml2/issues/378#issuecomment-352468512

**Comment by nigelmegitt** [comment]
> To be consistent with plans for this material in TTML2

It is consistent with TTML2 as it is now.

**Comment by palemieux** [comment]
@nigelmegitt I agree with @skynavga that the material would fit more nicely in Appendix N.2. Can it be moved there in both TTML1 and TTML2?

**Review by palemieux — CHANGES_REQUESTED** [review]
@nigelmegitt I agree with @skynavga that the material would fit more nicely in Appendix N.2. Can it be moved there in both TTML1 and TTML2?

**Comment by nigelmegitt** [comment]
@palemieux @skynavga OK but please raise the request to move it as a separate issue here and on ttml2 and I will then create the relevant pull requests.

**Comment by palemieux** [comment]
> OK but please raise the request to move it as a separate issue here and on ttml2 and I will then create the relevant pull requests.

@nigelmegitt Isn't this https://github.com/w3c/ttml2/issues/378 ?

**Comment by nigelmegitt** [comment]
> Isn't this w3c/ttml2#378 ?

Yes, for the ttml2 issue. Thanks for the pointer.

**Comment by palemieux** [comment]
@nigelmegitt TTML1 issue #300 already essentially says: "TTML1 should reflect TTML2". I therefore propose to implement https://github.com/w3c/ttml1/pull/319#pullrequestreview-89512972 under #300 in TTML1 and #378 for TTML2. You can close this PR, or update it.

**Comment by nigelmegitt** [comment]
@palemieux looking at the gamut of changes here, including introducing image files and references, in my view it'd be easier to merge this pull request and then implement the section move as a separate change in another PR.

**Comment by palemieux** [comment]
@nigelmegitt See https://github.com/w3c/ttml1/pull/334

**Comment by palemieux** [comment]
Replaced by #334 

@skynavga #334 is intended to address your [comment](https://github.com/w3c/ttml1/pull/319#pullrequestreview-87645568). Please review it.

**Pull request closed without merging**
