### PR TITLE
Remove bad character

### PR DESCRIPTION
**Pull request by MarcAntoine-Arnaud**

### CODE REVIEW

**Comment by cconcolato** [comment]
I don't understand where the bad character is. Can you explain?

**Comment by MarcAntoine-Arnaud** [comment]
3 bytes at the start. Invisible on text editors.
You can see them with an hex dump ...

**Comment by MarcAntoine-Arnaud** [comment]
You can see here, 3 first bytes with values: `0xef 0xbb 0xbf` precede the XML content

Screenshot 2020-05-28 at 10 50 23

**Comment by himorin** [comment]
ef bb bf is BOM for utf-8 text. I don't think we need this change.

**Comment by MarcAntoine-Arnaud** [comment]
Can make sense, but it's the only XSD with that information...

**Comment by MarcAntoine-Arnaud** [comment]
I have read more about BOM. And I have handled it in my tool.
It's the first time I found that, very interesting but not really common.

**Pull request closed without merging**
